### ISSUE TITLE
Grouping for weekly new music chart email should be case insensitive

### ISSUE THREAD

**Issue by Giggybyte** [wuvt/trackman#68]
Currently, for the weekly email that gets sent out, the case *is* considered:
```
1 : JEFF The Brotherhood - Magick Songs
...
1 : Jeff The Brotherhood - Magick Songs
```
Ideally, this should be two plays under the same author. 

The trivial solution, but maybe not the most optimal, would be to just lowercase everything: `2: jeff the brotherhood - magick songs`
There could be a little extra logic to re-capitalize words once the chart is tallied if we wanted to make things look pretty. Just an idea.

**Comment by echarlie** [comment]
One potential concern (at the risk of bikeshedding): this won't solve the problem of where DJs incorrectly enter unicode points (e.g. https://en.wikipedia.org/wiki/22,_A_Million). Those will still need to be handled manually.

I also don't know if lowercasing is the correct form of normalizing: since this is for a report to https://naccchart.com/, what is the "correct" form of normalization they want?
